@NutriTec.MongoApi_HostAddress = http://localhost:5272
@PacienteId = 11111111-1111-1111-1111-111111111111
@NutricionistaId = 22222222-2222-2222-2222-222222222222
@RetroalimentacionId = 33333333-3333-3333-3333-333333333333

POST {{NutriTec.MongoApi_HostAddress}}/api/retroalimentaciones
Content-Type: application/json

{
  "idPaciente": "{{PacienteId}}",
  "idNutricionista": "{{NutricionistaId}}",
  "autor": "Paciente",
  "mensaje": "Deseo revisar mi avance semanal."
}

###

GET {{NutriTec.MongoApi_HostAddress}}/api/retroalimentaciones/pacientes/{{PacienteId}}
Accept: application/json

###

GET {{NutriTec.MongoApi_HostAddress}}/api/retroalimentaciones/nutricionistas/{{NutricionistaId}}
Accept: application/json

###

POST {{NutriTec.MongoApi_HostAddress}}/api/retroalimentaciones/{{RetroalimentacionId}}/mensajes
Content-Type: application/json

{
  "autor": "Nutricionista",
  "mensaje": "Revisaremos las medidas en la próxima consulta."
}
